begin rewriting the configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-usage () {
+menu () {
 cat <<EOF
 
 hlibc 2018, CM Graff et al.
@@ -12,12 +12,13 @@ exit 0
 }
 
 print () {
-	printf "%s\n" "$*"
+	printf -- "%s\n" "$*"
 }
 
-fail () {
-	print "$*"
-	exit 1
+fatal()
+{
+        (>&2 print "fatal" "$*")
+        exit 1
 }
 
 fnmatch () { 
@@ -28,8 +29,15 @@ cmdexists () {
 	type "$1" >/dev/null 2>&1
 }
 
-trycc () { 
-	test -z "$CC" && cmdexists "$1" && CC=$1
+detectcommand()
+{
+        printf "trying $i .. "
+        if command -v "$1" >/dev/null 2>&1
+        then    print "yes"
+                return 0
+        else    print "no"
+                return 1
+        fi
 }
 
 setdir () {
@@ -52,25 +60,8 @@ tryflag () {
 	fi
 }
 
-tryldflag () {
-	printf "checking whether linker accepts %s... " "$2"
-	print "typedef int x;" > "$tmpc"
-	if "$CC" -nostdlib -shared "$2" -o /dev/null "$tmpc" 2>/dev/null
-	then	print "yes"
-		eval "$1=\"\${$1} \$2\""
-		eval "$1=\${$1# }"
-		return 0
-	else	print "no"
-		return 1
-	fi
-}
-
-# Beginning of actual script
-
-STACK_ALIGNMENT=
 CFLAGS_C99FSE=
 CFLAGS_AUTO=
-LDFLAGS_AUTO=
 prefix=
 exec_prefix=
 bindir=
@@ -85,7 +76,7 @@ static=yes
 
 for arg ; do
 	case "$arg" in
-		--help) usage ;;
+		--help) menu ;;
 		--prefix=*) prefix=${arg#*=} ;;
 		-* ) print "$0: unknown option $arg" ;;
 		CC=*) CC=${arg#*=} ;;
@@ -108,31 +99,40 @@ setdir syslibdir '/lib'
 # tempfile
 tmpc="./temporary_work_file"
 rm "$tmpc"
-trap 'rm "$tmpc"' EXIT INT QUIT TERM HUP
 
-
-# find a compiler
-printf "checking for C compiler... "
-trycc gcc
-trycc c99
-trycc cc
-trycc clang
-print "%s" "$CC"
-test -n "$CC" || { print "$0: cannot find a C compiler" ; exit 1 ; }
+print "Attempting to detect a C compiler ..."
+if [ -z "${CC}" ]
+then    for i in unlikely-cc c99 gcc cc clang pcc tcc
+        do      if detectcommand "$i"
+                then    CC="$i"
+                        break
+                fi
+        done
+        if [ -z "${CC}" ]
+        then    fatal "No compiler was able to be found. Giving up."
+        fi
+else    detectcommand "${CC}"
+fi
 
 
 # Find target architecture
-printf "checking target system type... "
+#printf "checking target system type... "
 test -n "$target" || target=$("$CC" -dumpmachine 2>/dev/null) || target=unknown
 print "%s" "$target"
 
 case "$target" in
-	arm*) ARCH=arm ;;
-	aarch64*) ARCH=aarch64 ;;
-	i?86*) ARCH=i386 ;;
-	x86_64*) ARCH=x86_64 ;;
-	unknown) fail "$0: unable to detect target arch; try $0 --target=..." ;;
-	*) fail "$0: unknown or unsupported target \"$target\"" ;;
+	arm*) ARCH=arm
+		;;
+	aarch64*) ARCH=aarch64
+		;;
+	i?86*) ARCH=i386
+		;;
+	x86_64*) ARCH=x86_64
+		;;
+	unknown) fatal "Architecture not found!!"
+		;;
+	*) fatal "Unknown architecture !!"
+		;;
 esac
 
 
@@ -159,7 +159,6 @@ fi
 tryflag CFLAGS_AUTO -fno-stack-protector
 tryflag DISABLE_PIE -fno-pie
 tryflag DISABLE_PIE -no-pie
-tryldflag LDFLAGS_AUTO -Wl,--hash-style=sysv
 
 print "Generating a config.mak for the main Makefile"
 
@@ -183,7 +182,6 @@ DISABLE_PIE = $DISABLE_PIE
 
 EOF
 test "x$static" = xno && print "STATIC_LIBS ="
-test "x$shared" = xno && print "SHARED_LIBS ="
 test "x$wrapper" = xno && print "ALL_TOOLS ="
 test "x$wrapper" = xno && print "TOOL_LIBS ="
 exec 1>&3 3>&-
